[tool.poetry]
name = "cs150241project-networking"
version = "0.2.2"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
websockets = "^14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

