"""
This type stub file was generated by pyright.
"""

import threading
import logging
from websockets.sync.client import ClientConnection
from typing import Generator, NewType
from dataclasses import dataclass

logger = ...
PlayerId = NewType('PlayerId', int)
def thread_id_filter(record: logging.LogRecord) -> logging.LogRecord:
    ...

@dataclass(frozen=True)
class Message:
    source: PlayerId
    payload: str
    @classmethod
    def from_raw(cls, raw: str) -> Message:
        ...
    
    def as_sendable(self) -> str:
        ...
    


class PlayerIdManager:
    def __init__(self) -> None:
        ...
    
    @property
    def pid_ready(self) -> bool:
        ...
    
    def set_pid(self, pid: PlayerId) -> None:
        ...
    
    def wait_for_pid(self) -> PlayerId:
        ...
    


class CS150241ProjectNetworking:
    def __init__(self) -> None:
        ...
    
    def close_all_threads(self) -> None:
        ...
    
    def sync_recv_loop(self, websocket: ClientConnection) -> None:
        ...
    
    def sync_send_loop(self, websocket: ClientConnection) -> None:
        ...
    
    def send(self, payload: str) -> None:
        ...
    
    def recv(self) -> Generator[Message, None, None]:
        ...
    
    def run_thread(self, ip_addr: str, port: int) -> threading.Thread:
        ...
    


if __name__ == "__main__":
    handler = ...
    networking = ...
    thread = ...
